fwd(FLStock) testing ... 
Fri Aug 15 20:40:21 2008 
========================

+ checkRun:  TRUE ; call:  checkRun(x = Target <- fwdTarget(year = 1998:2000, value = c(fbar(ple4)[1,      as.character(1998:2000)]), quantity = "f")) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkTrue:  TRUE ; call:  checkTrue(x = is(res, "FLStock")) 
+ checkEqual:  TRUE ; call:  checkEqual(x = fbar(ple4)[, as.character(1995:2000)], y = fbar(res)[,      as.character(1995:2000)]) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.4433001 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.3363397 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.2467722 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.08209343 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.2402693 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.4214477 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 3: Component 1: 1 string mismatch > Attributes: < Component 4: 1 string mismatch > ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > Mean relative difference: 0.2410381 ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Attributes: < Component 4: 1 string mismatch > ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  TRUE ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  TRUE ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  TRUE ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  TRUE ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  TRUE ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Lengths (1, 0) differ (string compare on first 0) ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  Lengths (1, 0) differ (string compare on first 0) ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkEqual:  TRUE ; call:  checkEqual(x = slot(ple4, i), y = slot(res, i)) 
+ checkRun:  TRUE ; call:  checkRun(x = Target <- fwdTarget(year = 1998:2000, value = c(2e+05,      210000, 220000), quantity = "ssb")) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkTrue:  TRUE ; call:  checkTrue(x = is(res, "FLStock")) 
+ checkEqual:  names for target but not for current ; call:  checkEqual(x = ssb(res)[1, as.character(2000:2001), drop = T],      y = Target[-1, "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkEqual:  names for target but not for current Mean relative difference: 0.126693 ; call:  checkEqual(x = c(ssb(res)[1, as.character(2000:2001), drop = T]),      y = c(ssb(res)[1, as.character(1995), drop = T]) * Target[-1,          "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = Target <- fwdTarget(year = 1998:2000, value = c(2e+05,      210000, 220000), quantity = "ssb")) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(res, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkEqual:  names for target but not for current Mean relative difference: 0.04122974 ; call:  checkEqual(x = ssb(res)[1, as.character(1998:2000), drop = T],      y = Target[, "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkEqual:  names for target but not for current ; call:  checkEqual(x = ssb(res)[1, as.character(1998:2000), drop = T],      y = c(ssb(res)[1, as.character(1995), drop = T]) * Target[,          "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = Target <- fwdTarget(year = 1998:2000, value = c(2e+05,      210000, 220000), quantity = "biomass")) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkTrue:  TRUE ; call:  checkTrue(x = is(res, "FLStock")) 
+ checkEqual:  names for target but not for current ; call:  checkEqual(x = computeStock(res)[1, as.character(2000:2001),      drop = T], y = Target[-1, "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkEqual:  names for target but not for current Mean relative difference: 0.0753691 ; call:  checkEqual(x = c(computeStock(res)[1, as.character(2000:2001),      drop = T]), y = c(computeStock(res)[1, as.character(1995),      drop = T]) * Target[-1, "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = Target <- fwdTarget(year = 1998:2000, value = c(2e+05,      210000, 220000), quantity = "catch")) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkTrue:  TRUE ; call:  checkTrue(x = is(res, "FLStock")) 
+ checkEqual:  names for target but not for current Mean relative difference: 3.429873 ; call:  checkEqual(x = c(computeCatch(res)[1, as.character(2000:2001),      drop = T]), y = c(Target[-1, "value"])) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkEqual:  names for target but not for current Mean relative difference: 1.137672 ; call:  checkEqual(x = c(computeCatch(res)[1, as.character(2000:2001),      drop = T]), y = c(computeCatch(res)[1, as.character(1995),      drop = T]) * Target[-1, "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = Target <- fwdTarget(year = 1998:2000, value = c(2e+05,      210000, 220000), quantity = "catch")) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkTrue:  TRUE ; call:  checkTrue(x = is(res, "FLStock")) 
+ checkEqual:  names for target but not for current Mean relative difference: 3.429873 ; call:  checkEqual(x = c(computeLandings(res)[1, as.character(2000:2001),      drop = T]), y = Target[-1, "value"]) 
+ checkRun:  TRUE ; call:  checkRun(x = res <- fwd(ple4, Target, sr.model = "geomean", sr.param = 25000)) 
+ checkEqual:  names for target but not for current Mean relative difference: 1.137672 ; call:  checkEqual(x = c(computeLandings(res)[1, as.character(2000:2001),      drop = T]), y = c(computeLandings(res)[1, as.character(1995),      drop = T]) * Target[-1, "value"]) 
